version: "3.5"

  
services:
  model:
    build: './pyClient'
    ports:
      - "5000:5000"

  stream:
    build: './modelStream'
    ports:
      - "7000:7000"
  
  web:
    container_name: go_web
    build: './goServer'
    ports:
      - "4000:3333"
    depends_on:
      - db
    restart: always
    
      
  db:
    container_name: postgres_container
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"